### ISSUE TITLE
Line item Buy X Get X Discounted

### ISSUE THREAD

**Issue by joeainsworth** [jgodson/shopify-script-creator#2]
I have created a Buy X Get X Discounted campaign where the customer must buy 10 items to get 10 items. The maximum sets is 2. My understanding would be that this discount would only apply when the customer has 10 or 20 items. However, if the customer has 11 items the discount is applied to all items. I would expect the discount to only be applied to 10 items until the next set of items have been met, which would be 20.

Is my understanding correct?

If so, then the following adjustment would make sense within `class BuyXGetX < Campaign`

~~discountable_quantity = (discountable_sets * @get_x).to_i~~
```discountable_quantity = purchased_quantity - (discountable_sets % @get_x).to_i```

When the cart has 11 qualifying items this will split the line so that 10 items are discounted and 1 item is full price. When the cart has 21 qualifying items this will split the line so that 20 items are discounted and 1 item is full price and so on.

**Comment by jgodson** [comment]
Thanks Joe, I'll take a look into this over the weekend

**Comment by jgodson** [comment]
Hey Joe, I didn't get to this as soon as I hoped, but I think changing this line
`discountable_sets = @max_sets ? [purchased_quantity / @buy_x, @max_sets].min : purchased_quantity / @buy_x` to `discountable_sets = (@max_sets ? [purchased_quantity / @buy_x, @max_sets].min : purchased_quantity / @buy_x).to_i` might be the fix for this. I'll do some more testing and ship a new version if so

**Comment by jgodson** [comment]
Just shipped a fix for this. Let me know if you see any issues. Thanks once again for your bug reports!
