### ISSUE TITLE
Payment gateway renamer

### ISSUE THREAD

**Issue by mathijsdelva-sylphar** [jgodson/shopify-script-creator#79]
Hi there,

It seems that the Payment Gateway renaming script does not seem to work anymore. Can you reproduce this? 

Reading through various threads on the internet, it seems this may be related to the fact that Shopify has updated its payment API and the way it required external payment providers to adjust their approach. Eg, since a few months, you are required to install actual "apps" as payment methods by using the app store (for example: https://apps.shopify.com/mollie-credit-card). 

Do you have any insight in this?

**Comment by jgodson** [comment]
Hello it's been a while since I worked with any payment gateway renaming so unfortunately I might not be of much help here.

I did check and I was able to rename `Credit card` as it shows up in checkout and the Script Editor app, however not using the name `Credit card`. I had to check in the code to see what the name actually was to input that as the name to change (see `puts gateway.name` below and the 3 results in the `Console` area). I imagine the name depends on what provider one is using here.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/12747574/215672077-4b6c631a-1ecc-41e0-a284-8b10ea3416f2.png">

<img width="578" alt="image" src="https://user-images.githubusercontent.com/12747574/215672540-c2605fc4-a0f9-424c-ad5f-1603b62c0f18.png">


I was not able to rename PayPal, but the [API docs](https://help.shopify.com/en/manual/checkout-settings/script-editor/shopify-scripts#payment-methods) do say you can't change any gateways with logos (which PayPal does have). The manual payment method I have can also be renamed by using it's name.

**Comment by mathijsdelva-sylphar** [comment]
Oh, i completely missed that small sentence in the documentation. Good eye. I've been in chat with Shopify Plus support for a while now and they never mentioned this, sigh. I let them know about the fact it is in the documentation so i can confirm that is the source of the issue. Meanwhile i'm using a small JS script to adjust the name of my desired payment gateway name. 

Thank you so much for taking a look!

**Comment by jgodson** [comment]
No problem, glad I could help out!
